### ISSUE TITLE
WaaS FeeOptions Support

### ISSUE THREAD

**Issue by taylanpince** [0xsequence/sequence-unreal#111]
Please add support for transaction fee options to the Unity WaaS SDK. In order to do that you need to:

1. Implement new Intent: https://github.com/0xsequence/go-sequence/blob/master/intents/intent.ridl#L76

    Modify send transaction to include fee option & quote and use fee option to add fee tx to the transaction list.

2. New send transaction intent: https://github.com/0xsequence/go-sequence/blob/master/intents/intent.ridl#L83

    Example API:
    https://github.com/0xsequence/sequence.js/blob/master/packages/waas/src/auth.ts#L422
    Example feeOprion -> tx:
    https://github.com/0xsequence/sequence.js/blob/master/packages/waas/src/intents/transactions.ts#L110
    Example Usage:
    https://github.com/0xsequence/demo-waas-auth/blob/tx-fee-options/src/components/views/SendTransactionsView.tsx#L98

If there are any question contact: @BellringerQuinn

**Comment by BellringerQuinn** [comment]
https://github.com/0xsequence/sequence-unity/pull/116/files

Unity implementation
