### ISSUE TITLE
Indexer - GetChainID - make this a non-async function

### ISSUE THREAD

**Issue by BellringerQuinn** [0xsequence/sequence-unreal#165]
No need to make a request to the sequence API for this. You can just return the cached value

Unity example: https://github.com/0xsequence/sequence-unity/blob/master/Packages/Sequence-Unity/Sequence/SequenceSDK/Indexer/ChainIndexer.cs#L88

**Comment by caballoninja** [comment]
That function is already included, its called Get Network Id
